### ISSUE TITLE
blacklist in argument triggers error

### ISSUE THREAD

**Issue by galtay** [openai/deeptype#13]
from README file,
```
python extraction/project_graph.py ${DATA_DIR}wikidata/ extraction/blacklist.json extraction/classifiers/type_classifier.py  --export_classification ${CLASSIFICATION_DIR}
```
having "extraction/blacklist.json" in the command makes the main function error out here (https://github.com/openai/deeptype/blob/master/extraction/project_graph.py#L87).  It looks like the blacklist is read no matter what here (https://github.com/openai/deeptype/blob/master/extraction/project_graph.py#L101)

**Comment by galtay** [comment]
added fix to #12

**Comment by karimvision** [comment]
+1
 i had this problem too, i changed the arguments manually to match those inside the file, i think i removed blacklist.json from the arguments when i ran this

**Comment by JonathanRaiman** [comment]
Yes. Readme used to manually specify location of the blacklist, while now it's always used (no real reason to have multiple blacklists. #12  is merged)
