### ISSUE TITLE
fix_destination is an undefined name in evaluate_type_system.py

### ISSUE THREAD

**Issue by cclauss** [openai/deeptype#2]
__fix_destination__ is an undefined name in [__this context__](https://github.com/openai/deeptype/blob/master/extraction/evaluate_type_system.py#L378).

flake8 testing of https://github.com/openai/deeptype on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./extraction/evaluate_type_system.py:378:29: F821 undefined name 'fix_destination'
            fix_destination=fix_destination,
                            ^
``

**Comment by JonathanRaiman** [comment]
Typo, thanks for pointing this out :) should now be fixed!
