### ISSUE TITLE
ModuleNotFoundError: No module named 'wikidata_linker_utils.successor_mask'

### ISSUE THREAD

**Issue by MurtyShikhar** [openai/deeptype#20]
I get this while trying to run /extraction/full_preprocess.sh ${DATA_DIR} en. I have installed all the dependencies. What could be going wrong?

**Comment by onijinsky** [comment]
I have the same problem, someone know how to deal with it?

**Comment by tbarnier** [comment]
I 've got the feeling I faced this problem

At some point, I had to install a sspecific version of epub-conversion

would 
pip install epub-conversion==1.0.8

help?
