### ISSUE TITLE
the paper is hard to understand

### ISSUE THREAD

**Issue by herbertchen1** [openai/deeptype#24]
In the last of the section 3, i find the scoring function S(e,m,D,A,θ) ,argmax it to get the optimal entity.

however ,the formulation seems have no relation with the candidate entity, it's just Plink(e,m) mutiply a constant given a single mention.
I don't know whether i have a bad understanding of the paper，or maybe Pi,*（m） need to multiply a deterministic Pi,*（e） which is got from the wikidata?
sincerely hope for your answer.

**Comment by JonathanRaiman** [comment]
Thanks you for bringing this up. Hopefully the following clarifies this point.

I believe you are referring to equation (6), where the scoring function is defined. In this case `P_i (t_i, m, D)` is a function that estimates the likelihood of mention `m` from document `D` belonging to type `t_i`. Each entity has a set of associated types that defines it (so `Types(e) = {t_1, ..., t_k}`), hence `t_i` is actually a property of e (apologies for omission of the subscript e in `t_i`). The paragraph above introduces `t_i`. Hope this helps!

**Comment by herbertchen1** [comment]
Thanks for your answer！！！
