### ISSUE TITLE
evaluation method

### ISSUE THREAD

**Issue by karimvision** [openai/deeptype#29]
Hi! It would be great if you could tell us how you evaluated the system, since the model outputs types, did you use types to evaluate the system or did you use the wiki entities extracted from the types? As wiki entities would require entity normalization (British = United Kingdom = Great Britain= European Nation = ,,etc), this would be helpful in evaluating the models we trained, thanks!

**Comment by karimvision** [comment]
duplicate of #27 closing ...

**Comment by karimvision** [comment]
and duplicate of #26

**Comment by mailong25** [comment]
@karimvision
Have you found the solution yet ?
