### ISSUE TITLE
total is an undefined name in evolve_type_system.py

### ISSUE THREAD

**Issue by cclauss** [openai/deeptype#3]
__total__ is an undefined name in [__this context__](https://github.com/openai/deeptype/blob/master/extraction/evolve_type_system.py#L99-L100).

flake8 testing of https://github.com/openai/deeptype on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./extraction/evolve_type_system.py:99:34: F821 undefined name 'total'
        return (greedy_correct / total,
                                 ^
./extraction/evolve_type_system.py:100:34: F821 undefined name 'total'
                greedy_correct / total)
                                 ^
```

**Comment by JonathanRaiman** [comment]
Typo, thanks for pointing this out :) fixed now
