### ISSUE TITLE
tags is an undefined name in train_type.py

### ISSUE THREAD

**Issue by cclauss** [openai/deeptype#4]
__tags__ is an undefined name in [__this context__](https://github.com/openai/deeptype/blob/master/learning/train_type.py#L2442).

flake8 testing of https://github.com/openai/deeptype on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./learning/train_type.py:2442:67: F821 undefined name 'tags'
                        for tokens, tags, score in zip(sentences, tags, scores)
                                                                  ^
```

**Comment by JonathanRaiman** [comment]
Typo, thanks for finding this!
